package com.iexceed.appzillonbanking.cob.core.repository.ab;

import com.iexceed.appzillonbanking.cob.core.domain.ab.ApplicationMaster;
import com.iexceed.appzillonbanking.cob.core.domain.ab.ApplicationMasterId;
import com.iexceed.appzillonbanking.cob.payload.MasterSearchQueryDTO;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;

@Repository
@Transactional(transactionManager = "abCOBTransactionManager")
public interface ApplicationMasterRepository2 extends JpaRepository<ApplicationMaster, ApplicationMasterId> {

    @Query("SELECT a.applicationStatus FROM ApplicationMaster a WHERE a.appId = :appId AND a.applicationId = :applicationId")
    String findApplicationStatus(@Param("appId") String appId, @Param("applicationId") String applicationId);


    @Query(value = "SELECT new ApplicationMaster(0L, 0L, "
            + " COUNT(DISTINCT CASE WHEN app.applicationStatus IN :sourcingStatus THEN app.applicationId END), "
            + " COUNT(DISTINCT CASE WHEN app.applicationStatus IN :bmApprovalStatus THEN app.applicationId END), "
            + " COUNT(DISTINCT CASE WHEN app.applicationStatus IN (:rpcVerificationStatus) "
            + " AND app.declarationFlag = :iexceedFlag THEN app.applicationId END), "
            + " COUNT(DISTINCT CASE WHEN app.applicationStatus IN :creditAssessmentStatus THEN app.applicationId END), "
            + " COUNT(DISTINCT CASE WHEN app.applicationStatus IN :deviationRAStatus AND EXISTS ( "
            + " SELECT 1 FROM DeviationRATracker deviationRa1 WHERE deviationRa1.applicationId = app.applicationId AND "
            + " deviationRa1.authority = :userRoleKey "
            + " AND deviationRa1.recordType IN :recordType ) THEN app.applicationId END), "
            + " COUNT(DISTINCT CASE "
            + " WHEN app.applicationStatus = 'CACOMPLETED' "
            + " AND ("
            + " (:userRoleKey = 'BM' AND sanctionMaster.bm = 'Y') OR "
            + " (:userRoleKey = 'AM' AND sanctionMaster.am = 'Y') OR "
            + " (:userRoleKey = 'RM' AND sanctionMaster.rm = 'Y') OR "
            + " (:userRoleKey = 'DM' AND sanctionMaster.dm = 'Y') "
            + " ) "
            + " AND loanDtl.bmRecommendedLoanAmount BETWEEN sanctionMaster.minValue AND sanctionMaster.maxValue "
            + "     THEN app.applicationId "
            + "     WHEN app.applicationStatus = 'RESANCTION' "
            + " AND ("
            + "     (:userRoleKey = 'BM' AND sanctionMaster.bm = 'Y') OR "
            + "     (:userRoleKey = 'AM' AND sanctionMaster.am = 'Y') OR "
            + "     (:userRoleKey = 'RM' AND sanctionMaster.rm = 'Y') OR "
            + "     (:userRoleKey = 'DM' AND sanctionMaster.dm = 'Y') "
            + " ) "
            + " AND cbDtls.eligibleAmt BETWEEN sanctionMaster.minValue AND sanctionMaster.maxValue "
            + "     THEN app.applicationId "
            + "     WHEN app.applicationStatus = 'PENDINGPRESANCTION' THEN app.applicationId "
            + " END), "
            + " COUNT(DISTINCT CASE WHEN app.applicationStatus IN :disbursementInprogressStatus THEN app.applicationId END), "
            + " COUNT(DISTINCT CASE WHEN app.applicationStatus IN :disbursedStatus THEN app.applicationId END), "
            + " COUNT(DISTINCT CASE WHEN (app.applicationStatus IN :postDisbursementStatus AND aw3.createTs <= :DWaitDateTime) "
            + " OR (app.applicationStatus = 'LUC' AND prevAw.applicationStatus = 'PENDINGLUCVERIFICATION')THEN app.applicationId END), "
            + " COUNT(DISTINCT CASE WHEN app.applicationStatus IN :rejectedStatus THEN app.applicationId END)) "
            + " FROM ApplicationMaster app "
            + " LEFT JOIN LoanDetails loanDtl ON app.applicationId = loanDtl.applicationId "
            + " LEFT JOIN SanctionMaster sanctionMaster ON app.productCode = sanctionMaster.product "
            + " LEFT JOIN ApplicationWorkflow aw ON app.applicationId = aw.applicationId AND aw.workflowSeqNum = ("
            + " SELECT MAX(aw2.workflowSeqNum) FROM ApplicationWorkflow aw2 WHERE aw2.applicationId = app.applicationId )"
            + " LEFT JOIN ApplicationWorkflow prevAw ON app.applicationId = prevAw.applicationId AND prevAw.workflowSeqNum = ( "
            + " SELECT MAX(p.workflowSeqNum) FROM ApplicationWorkflow p WHERE p.applicationId = aw.applicationId AND p.workflowSeqNum < aw.workflowSeqNum ) "
            + " LEFT JOIN ApplicationWorkflow aw3 ON app.applicationId = aw3.applicationId AND aw3.applicationStatus IN :postDisbursementStatus "
            + " AND aw3.workflowSeqNum = aw.workflowSeqNum "
            + " LEFT JOIN CibilDetails cbDtls ON app.applicationId = cbDtls.applicationId and cbDtls.custDtlId = ( "
            + " SELECT cd.custDtlId from CustomerDetails cd WHERE cd.applicationId = app.applicationId and cd.customerType = 'Co-App' )"
            + " WHERE app.productCode IN :productCodes AND app.branchId IN :branches ")
    ApplicationMaster fetchDashboardCount(
            List<String> branches,
            List<String> sourcingStatus,
            List<String> bmApprovalStatus,
            List<String> rpcVerificationStatus,
            List<String> creditAssessmentStatus,
            List<String> deviationRAStatus,
            List<String> disbursementInprogressStatus,
            List<String> disbursedStatus,
            List<String> rejectedStatus,
            List<String> postDisbursementStatus,
            String userRoleKey,
            List<String> recordType, List<String> productCodes, String iexceedFlag,LocalDateTime DWaitDateTime);


    @Query(value = "SELECT new ApplicationMaster(0L, 0L, "
            + " (COUNT(CASE WHEN app.applicationStatus IN :sourcingStatus THEN 1 END)) AS sourcingCount, "
            + " (COUNT(CASE WHEN app.applicationStatus IN :bmApprovalStatus THEN 1 END)) AS bmApprovalCount, "
            + " (COUNT(CASE WHEN app.applicationStatus IN :rpcVerificationStatus THEN 1 END)) AS rpcVerificationCount, "
            + " (COUNT(CASE WHEN app.applicationStatus IN :creditAssessmentStatus THEN 1 END)) AS creditAssessmentCount, "
            + " (COUNT(CASE WHEN app.applicationStatus IN :deviationRAStatus THEN 1 END)) AS deviationRACount, "
            + " (COUNT(CASE WHEN app.applicationStatus IN :sanctionStatus THEN 1 END)) AS sanctionCount, "
            + " (COUNT(CASE WHEN app.applicationStatus IN :disbursementInprogressStatus THEN 1 END)) AS disbursementInprogressCount, "
            + " (COUNT(CASE WHEN app.applicationStatus IN :disbursedStatus THEN 1 END)) AS disbursedCount, "
            + " COUNT(DISTINCT CASE WHEN (app.applicationStatus IN :postDisbursementStatus AND aw3.createTs <= :DKmWaitDateTime) "
            + " OR (app.applicationStatus = 'LUC' AND prevAw.applicationStatus = 'PENDINGLUCVERIFICATION')THEN app.applicationId END) AS postDisbursementCount, "
            + " (COUNT(CASE WHEN app.applicationStatus IN :rejectedStatus AND aw.createTs <= :rejectionExpiryDateTime THEN 1 END)) AS rejectedCount) "
            + " FROM ApplicationMaster app LEFT JOIN ApplicationWorkflow aw ON app.applicationId = aw.applicationId AND aw.workflowSeqNum = ("
            + " SELECT MAX(aw2.workflowSeqNum) FROM ApplicationWorkflow aw2 WHERE aw2.applicationId = app.applicationId )"
            + " LEFT JOIN ApplicationWorkflow aw3 ON app.applicationId = aw3.applicationId AND aw3.applicationStatus IN :postDisbursementStatus AND aw3.workflowSeqNum = aw.workflowSeqNum "
            + " LEFT JOIN ApplicationWorkflow prevAw ON app.applicationId = prevAw.applicationId AND prevAw.workflowSeqNum = ( "
            + " SELECT MAX(p.workflowSeqNum) FROM ApplicationWorkflow p WHERE p.applicationId = aw.applicationId AND p.workflowSeqNum < aw.workflowSeqNum ) "
            + " WHERE app.searchCode1 IN :kendraIds AND app.productCode IN :productCodes ")
     ApplicationMaster fetchKMDashboardCount(
            List<String> kendraIds,
            List<String> sourcingStatus,
            List<String> bmApprovalStatus,
            List<String> rpcVerificationStatus,
            List<String> creditAssessmentStatus,
            List<String> deviationRAStatus,
            List<String> sanctionStatus,
            List<String> disbursementInprogressStatus,
            List<String> disbursedStatus,
            List<String> rejectedStatus,List<String> postDisbursementStatus, List<String> productCodes, LocalDateTime rejectionExpiryDateTime,LocalDateTime DKmWaitDateTime);

    @Query(value = "SELECT new ApplicationMaster( "
            + "appMaster1.applicationId AS applicationId, "
            + "appMaster1.memberId AS customerId, "
            + "custdtls.customerName AS customerName, "
            + "appMaster1.branchName AS branchName, "
            + "CONCAT("
            + "FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60) * 60), 'S|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600) * 60), 'M|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400) * 24), 'H|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400), 'D' ) AS rpcTAT,"
            + "loanDtl.loanAmount AS loanAmount,"
            + " appMaster1.applicationStatus as applicationStatus, "
            + " CASE WHEN COUNT(appWfl.applicationId) > 0 THEN 'true' ELSE 'false' END AS isRework ) "
            + " FROM ApplicationMaster appMaster1 "
            + "LEFT JOIN LoanDetails loanDtl ON appMaster1.applicationId = loanDtl.applicationId "
            + "LEFT JOIN ApplicationWorkflow applnWf1 ON appMaster1.applicationId = applnWf1.applicationId "
            + "LEFT JOIN CustomerDetails custdtls ON appMaster1.applicationId = custdtls.applicationId "
            + "AND custdtls.customerType = 'Applicant' "
            + " LEFT JOIN ApplicationWorkflow appWfl ON appMaster1.applicationId = appWfl.applicationId "
            + " AND appWfl.applicationStatus IN (:reworkStatus) "
            + " WHERE appMaster1.branchId IN :branches AND appMaster1.applicationStatus IN :rPCDBVerificationStatusList "
            + " AND applnWf1.workflowSeqNum = ("
            + " SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 "
            + " WHERE applnWf2.applicationId = appMaster1.applicationId) "
            + " AND ("
            + "    (:filterType = 'ALL' "
            + "        AND appMaster1.applicationStatus IN (:rPCDBVerificationStatusList)) "
            + "    OR (:filterType = 'FRESHCASES' "
            + "        AND appMaster1.applicationStatus IN (:rPCDBVerificationStatusList) "
            + "        AND NOT EXISTS ( "
            + "            SELECT 1 "
            + "            FROM ApplicationWorkflow wf "
            + "            WHERE wf.applicationId = appMaster1.applicationId "
            + "              AND wf.applicationStatus IN (:reworkStatus))) "
            + "    OR (:filterType = 'REWORKCASES' "
            + "        AND appMaster1.applicationStatus IN (:rPCDBVerificationStatusList) "
            + "        AND EXISTS ( "
            + "            SELECT 1 "
            + "            FROM ApplicationWorkflow wf "
            + "            WHERE wf.applicationId = appMaster1.applicationId "
            + "              AND wf.applicationStatus IN (:reworkStatus))) "
            + ") "
            + " GROUP BY appMaster1.applicationId, "
            + " appMaster1.memberId, "
            + " custdtls.customerName,"
            + " appMaster1.branchName, "
            + " loanDtl.loanAmount, "
            + " appMaster1.applicationStatus, appMaster1.createTs, "
            + " applnWf1.createTs, applnWf1.workflowSeqNum "
            + " ORDER BY EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) ASC")
     Page<ApplicationMaster> fetchRPCDBVerificationDashboardApplications(
            @Param("rPCDBVerificationStatusList") List<String> rPCDBVerificationStatusList,
            @Param("branches") List<String> branches, Pageable page, @Param("filterType") String filterType,
            @Param("reworkStatus") List<String> reworkStatus);

    @Query(value = "SELECT new ApplicationMaster( "
            + "appMaster1.applicationId AS applicationId, "
            + "appMaster1.memberId AS customerId, "
            + "custdtls.customerName AS customerName, "
            + "appMaster1.branchName AS branchName, "
            + "CONCAT("
            + "FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60) * 60), 'S|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600) * 60), 'M|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400) * 24), 'H|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400), 'D' ) AS rpcTAT,"
            + "loanDtl.loanAmount AS loanAmount,"
            + " appMaster1.applicationStatus as applicationStatus, '') "
            + " FROM ApplicationMaster appMaster1 "
            + "LEFT JOIN LoanDetails loanDtl ON appMaster1.applicationId = loanDtl.applicationId "
            + "LEFT JOIN ApplicationWorkflow applnWf1 ON appMaster1.applicationId = applnWf1.applicationId "
            + "LEFT JOIN CustomerDetails custdtls ON appMaster1.applicationId = custdtls.applicationId "
            + "AND custdtls.customerType = 'Applicant' "
            + " WHERE appMaster1.searchCode1 IN :kendraIds AND appMaster1.applicationStatus IN :rPCDBVerificationStatusList "
            + " AND applnWf1.workflowSeqNum = ("
            + " SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 "
            + " WHERE applnWf2.applicationId = appMaster1.applicationId) AND appMaster1.productCode IN :productCodes "
            + " AND ("
            + "    (:filterType = 'ALL' "
            + "        AND appMaster1.applicationStatus IN (:rPCDBVerificationStatusList)) "
            + "    OR (:filterType = 'FRESHCASES' "
            + "        AND appMaster1.applicationStatus IN (:rPCDBVerificationStatusList) "
            + "        AND NOT EXISTS ( "
            + "            SELECT 1 "
            + "            FROM ApplicationWorkflow wf "
            + "            WHERE wf.applicationId = appMaster1.applicationId "
            + "              AND wf.applicationStatus IN (:reworkStatus))) "
            + "    OR (:filterType = 'REWORKCASES' "
            + "        AND appMaster1.applicationStatus IN (:rPCDBVerificationStatusList) "
            + "        AND EXISTS ( "
            + "            SELECT 1 "
            + "            FROM ApplicationWorkflow wf "
            + "            WHERE wf.applicationId = appMaster1.applicationId "
            + "              AND wf.applicationStatus IN (:reworkStatus))) "
            + ") "
            + " GROUP BY appMaster1.applicationId, "
            + " appMaster1.memberId, "
            + " custdtls.customerName,"
            + " appMaster1.branchName, "
            + " loanDtl.loanAmount, "
            + " appMaster1.applicationStatus, appMaster1.createTs, "
            + " applnWf1.createTs, applnWf1.workflowSeqNum "
            + " ORDER BY EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) ASC")
     Page<ApplicationMaster> fetchRPCDBVerificationForKMDashboardApplications(
            @Param("rPCDBVerificationStatusList") List<String> rPCDBVerificationStatusList,
            @Param("kendraIds") List<String> kendraIds, Pageable page, @Param("filterType") String filterType,
            @Param("reworkStatus") List<String> reworkStatus, List<String> productCodes);

    @Query(value = "SELECT new ApplicationMaster( "
            + "appMaster1.applicationId AS applicationId, "
            + "appMaster1.memberId AS customerId, "
            + "custdtls.customerName AS customerName, "
            + "appMaster1.branchName AS branchName, "
            + "CONCAT("
            + "FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60) * 60), 'S|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600) * 60), 'M|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400) * 24), 'H|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400), 'D' ) AS rpcTAT,"
            + "loanDtl.loanAmount AS loanAmount,"
            + " appMaster1.applicationStatus as applicationStatus, "
            + " CASE WHEN COUNT(appWfl.applicationId) > 0 THEN 'true' ELSE 'false' END AS isRework ) "
            + " FROM ApplicationMaster appMaster1 "
            + "LEFT JOIN LoanDetails loanDtl ON appMaster1.applicationId = loanDtl.applicationId "
            + "LEFT JOIN ApplicationWorkflow applnWf1 ON appMaster1.applicationId = applnWf1.applicationId "
            + "LEFT JOIN CustomerDetails custdtls ON appMaster1.applicationId = custdtls.applicationId "
            + "AND custdtls.customerType = 'Applicant' "
            + " LEFT JOIN ApplicationWorkflow appWfl ON appMaster1.applicationId = appWfl.applicationId "
            + " AND appWfl.applicationStatus IN (:reworkStatus) "
            + " WHERE appMaster1.branchId IN :branches AND appMaster1.applicationStatus IN :rPCDBVerificationStatusList "
            + " AND applnWf1.workflowSeqNum = ("
            + " SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 "
            + " WHERE applnWf2.applicationId = appMaster1.applicationId) AND "
            + " (LOWER(appMaster1.applicationId) = LOWER(:searchVal) OR "
            + " LOWER(appMaster1.memberId) = LOWER(:searchVal) OR LOWER(appMaster1.branchName) = LOWER(:searchVal) OR "
            + " LOWER(appMaster1.alternateVoterId) = LOWER(:searchVal) OR "
            + " LOWER(appMaster1.primaryKycId) = LOWER(:searchVal) OR LOWER(appMaster1.secondaryKycId) = LOWER(:searchVal) "
            + " OR LOWER(custdtls.mobileNumber) = LOWER(:searchVal))"
            + " AND ("
            + "    (:filterType = 'ALL' "
            + "        AND appMaster1.applicationStatus IN (:rPCDBVerificationStatusList)) "
            + "    OR (:filterType = 'FRESHCASES' "
            + "        AND appMaster1.applicationStatus IN (:rPCDBVerificationStatusList) "
            + "        AND NOT EXISTS ( "
            + "            SELECT 1 "
            + "            FROM ApplicationWorkflow wf "
            + "            WHERE wf.applicationId = appMaster1.applicationId "
            + "              AND wf.applicationStatus IN (:reworkStatus))) "
            + "    OR (:filterType = 'REWORKCASES' "
            + "        AND appMaster1.applicationStatus IN (:rPCDBVerificationStatusList) "
            + "        AND EXISTS ( "
            + "            SELECT 1 "
            + "            FROM ApplicationWorkflow wf "
            + "            WHERE wf.applicationId = appMaster1.applicationId "
            + "              AND wf.applicationStatus IN (:reworkStatus))) "
            + ") "
            + " GROUP BY appMaster1.applicationId, "
            + " appMaster1.memberId, "
            + " custdtls.customerName,"
            + " appMaster1.branchName, "
            + " loanDtl.loanAmount, "
            + " appMaster1.applicationStatus, appMaster1.createTs, "
            + " applnWf1.createTs, applnWf1.workflowSeqNum "
            + " ORDER BY EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) ASC")
     Page<ApplicationMaster> fetchRPCDBVerificationDashboardApplicationsSearch(
            @Param("rPCDBVerificationStatusList") List<String> rPCDBVerificationStatusList,
            @Param("branches") List<String> branches, Pageable page, @Param("filterType") String filterType,
            @Param("reworkStatus") List<String> reworkStatus, @Param("searchVal") String searchVal);

    @Query(value = "SELECT new ApplicationMaster( "
            + "appMaster1.applicationId AS applicationId, "
            + "appMaster1.memberId AS customerId, "
            + "custdtls.customerName AS customerName, "
            + "appMaster1.branchName AS branchName, "
            + "CONCAT("
            + "FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60) * 60), 'S|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600) * 60), 'M|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400) * 24), 'H|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400), 'D' ) AS rpcTAT,"
            + "loanDtl.loanAmount AS loanAmount,"
            + " appMaster1.applicationStatus as applicationStatus, '') "
            + " FROM ApplicationMaster appMaster1 "
            + "LEFT JOIN LoanDetails loanDtl ON appMaster1.applicationId = loanDtl.applicationId "
            + "LEFT JOIN ApplicationWorkflow applnWf1 ON appMaster1.applicationId = applnWf1.applicationId "
            + "LEFT JOIN CustomerDetails custdtls ON appMaster1.applicationId = custdtls.applicationId "
            + "AND custdtls.customerType = 'Applicant' "
            + " WHERE appMaster1.branchId IN :branches AND appMaster1.applicationStatus = :filterType "
            + " AND applnWf1.workflowSeqNum = ("
            + " SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 "
            + " WHERE applnWf2.applicationId = appMaster1.applicationId) "
            + " GROUP BY appMaster1.applicationId, "
            + " appMaster1.memberId, "
            + " custdtls.customerName,"
            + " appMaster1.branchName, "
            + " loanDtl.loanAmount, "
            + " appMaster1.applicationStatus, appMaster1.createTs, "
            + " applnWf1.createTs, applnWf1.workflowSeqNum "
            + " ORDER BY EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) ASC")
     Page<ApplicationMaster> fetchRPCDBVerificationDashboardALTApplications(
            @Param("branches") List<String> branches, Pageable page, @Param("filterType") String filterType
    );

    @Query(value = "SELECT new ApplicationMaster( "
            + "appMaster1.applicationId AS applicationId, "
            + "appMaster1.memberId AS customerId, "
            + "custdtls.customerName AS customerName, "
            + "appMaster1.branchName AS branchName, "
            + "CONCAT("
            + "FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60) * 60), 'S|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600) * 60), 'M|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400) * 24), 'H|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400), 'D' ) AS rpcTAT,"
            + "loanDtl.loanAmount AS loanAmount,"
            + " appMaster1.applicationStatus as applicationStatus, '') "
            + " FROM ApplicationMaster appMaster1 "
            + "LEFT JOIN LoanDetails loanDtl ON appMaster1.applicationId = loanDtl.applicationId "
            + "LEFT JOIN ApplicationWorkflow applnWf1 ON appMaster1.applicationId = applnWf1.applicationId "
            + "LEFT JOIN CustomerDetails custdtls ON appMaster1.applicationId = custdtls.applicationId "
            + "AND custdtls.customerType = 'Applicant' "
            + " WHERE appMaster1.branchId IN :branches AND appMaster1.applicationStatus = :filterType "
            + " AND applnWf1.workflowSeqNum = ("
            + " SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 "
            + " WHERE applnWf2.applicationId = appMaster1.applicationId) AND "
            + " (LOWER(appMaster1.applicationId) = LOWER(:searchVal) OR "
            + " LOWER(appMaster1.memberId) = LOWER(:searchVal) OR LOWER(appMaster1.branchName) = LOWER(:searchVal) OR "
            + " LOWER(appMaster1.alternateVoterId) = LOWER(:searchVal) OR "
            + " LOWER(appMaster1.primaryKycId) = LOWER(:searchVal) OR LOWER(appMaster1.secondaryKycId) = LOWER(:searchVal) "
            + " OR LOWER(custdtls.mobileNumber) = LOWER(:searchVal))"
            + " GROUP BY appMaster1.applicationId, "
            + " appMaster1.memberId, "
            + " custdtls.customerName,"
            + " appMaster1.branchName, "
            + " loanDtl.loanAmount, "
            + " appMaster1.applicationStatus, appMaster1.createTs, "
            + " applnWf1.createTs, applnWf1.workflowSeqNum "
            + " ORDER BY EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) ASC")
     Page<ApplicationMaster> fetchRPCDBVerificationDashboardALTApplicationsSearch(
            @Param("branches") List<String> branches, Pageable page, @Param("filterType") String filterType,
            @Param("searchVal") String searchVal);

    @Query(value = "SELECT new ApplicationMaster( "
            + "COUNT(CASE WHEN appMaster1.applicationStatus IN :rPCDBVerificationStatusList THEN 1 END) AS totalApplications, "
            + "COUNT(CASE WHEN appMaster1.applicationStatus IN :rPCDBVerificationStatusList "
            + "    AND NOT EXISTS ( "
            + "        SELECT 1 FROM ApplicationWorkflow wf "
            + "        WHERE wf.applicationId = appMaster1.applicationId "
            + "        AND wf.applicationStatus IN (:reworkStatus) "
            + "    ) THEN 1 END) AS freshCases, "
            + "COUNT(CASE WHEN appMaster1.applicationStatus IN :rPCDBVerificationStatusList "
            + "    AND EXISTS ( "
            + "        SELECT 1 FROM ApplicationWorkflow wf "
            + "        WHERE wf.applicationId = appMaster1.applicationId "
            + "        AND wf.applicationStatus IN (:reworkStatus) "
            + "    ) THEN 1 END) AS reworkCases, "
            + " 0L, "
            + "COUNT(CASE WHEN appMaster1.applicationStatus IN :dbPushbackStatus THEN 1 END) AS pushbackCases, "
            + "COUNT(CASE WHEN appMaster1.applicationStatus IN :dbKitVerifiedStatus THEN 1 END) AS completedCases, "
            + "COUNT(CASE WHEN appMaster1.applicationStatus IN :rPCDBVerificationStatusList "
            + "    AND EXISTS ( "
            + "        SELECT 1 FROM ApplicationWorkflow wf "
            + "        WHERE wf.applicationId = appMaster1.applicationId "
            + "        AND wf.workflowSeqNum = ( "
            + "            SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 "
            + "            WHERE applnWf2.applicationId = appMaster1.applicationId "
            + "        ) "
            + "        AND FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, wf.createTs)) / 86400) = 0 "
            + "    ) THEN 1 END) AS dayZero, "
            + "COUNT(CASE WHEN appMaster1.applicationStatus IN :rPCDBVerificationStatusList "
            + "    AND EXISTS ( "
            + "        SELECT 1 FROM ApplicationWorkflow wf "
            + "        WHERE wf.applicationId = appMaster1.applicationId "
            + "        AND wf.workflowSeqNum = ( "
            + "            SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 "
            + "            WHERE applnWf2.applicationId = appMaster1.applicationId "
            + "        ) "
            + "        AND FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, wf.createTs)) / 86400) = 1 "
            + "    ) THEN 1 END) AS dayOne, "
            + "COUNT(CASE WHEN appMaster1.applicationStatus IN :rPCDBVerificationStatusList "
            + "    AND EXISTS ( "
            + "        SELECT 1 FROM ApplicationWorkflow wf "
            + "        WHERE wf.applicationId = appMaster1.applicationId "
            + "        AND wf.workflowSeqNum = ( "
            + "            SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 "
            + "            WHERE applnWf2.applicationId = appMaster1.applicationId "
            + "        ) "
            + "        AND FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, wf.createTs)) / 86400) = 2 "
            + "    ) THEN 1 END) AS dayTwo, "
            + "COUNT(CASE WHEN appMaster1.applicationStatus IN :rPCDBVerificationStatusList "
            + "    AND EXISTS ( "
            + "        SELECT 1 FROM ApplicationWorkflow wf "
            + "        WHERE wf.applicationId = appMaster1.applicationId "
            + "        AND wf.workflowSeqNum = ( "
            + "            SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 "
            + "            WHERE applnWf2.applicationId = appMaster1.applicationId "
            + "        ) "
            + "        AND FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, wf.createTs)) / 86400) = 3 "
            + "    ) THEN 1 END) AS dayThree, "
            + "COUNT(CASE WHEN appMaster1.applicationStatus IN :rPCDBVerificationStatusList "
            + "    AND EXISTS ( "
            + "        SELECT 1 FROM ApplicationWorkflow wf "
            + "        WHERE wf.applicationId = appMaster1.applicationId "
            + "        AND wf.workflowSeqNum = ( "
            + "            SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 "
            + "            WHERE applnWf2.applicationId = appMaster1.applicationId "
            + "        ) "
            + "        AND FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, wf.createTs)) / 86400) = 4 "
            + "    ) THEN 1 END) AS dayFour, "
            + "COUNT(CASE WHEN appMaster1.applicationStatus IN :rPCDBVerificationStatusList "
            + "    AND EXISTS ( "
            + "        SELECT 1 FROM ApplicationWorkflow wf "
            + "        WHERE wf.applicationId = appMaster1.applicationId "
            + "        AND wf.workflowSeqNum = ( "
            + "            SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 "
            + "            WHERE applnWf2.applicationId = appMaster1.applicationId "
            + "        ) "
            + "        AND FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, wf.createTs)) / 86400) = 5 "
            + "    ) THEN 1 END) AS dayFive, "
            + "COUNT(CASE WHEN appMaster1.applicationStatus IN :rPCDBVerificationStatusList "
            + "    AND EXISTS ( "
            + "        SELECT 1 FROM ApplicationWorkflow wf "
            + "        WHERE wf.applicationId = appMaster1.applicationId "
            + "        AND wf.workflowSeqNum = ( "
            + "            SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 "
            + "            WHERE applnWf2.applicationId = appMaster1.applicationId "
            + "        ) "
            + "        AND FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, wf.createTs)) / 86400) > 5 "
            + "    ) THEN 1 END) AS moreThanFiveDays "
            + ") "
            + "FROM ApplicationMaster appMaster1 "
            + "LEFT JOIN ApplicationWorkflow applnWf1 ON appMaster1.applicationId = applnWf1.applicationId "
            + "LEFT JOIN CustomerDetails custdtls ON appMaster1.applicationId = custdtls.applicationId "
            + "WHERE appMaster1.branchId IN :branches "
            + "AND appMaster1.applicationStatus IN :rpcDbVerificationAllowedStatus "
            + "AND custdtls.customerType = 'Applicant' "
            + "AND applnWf1.workflowSeqNum = ( "
            + "    SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 "
            + "    WHERE applnWf2.applicationId = appMaster1.applicationId "
            + ")")
     ApplicationMaster fetchRPCDBVerificationDashboardCounts(
            @Param("rPCDBVerificationStatusList") List<String> rPCDBVerificationStatusList,
            @Param("branches") List<String> branches,
            @Param("reworkStatus") List<String> reworkStatus,
            @Param("dbKitVerifiedStatus") List<String> dbKitVerifiedStatus,
            @Param("dbPushbackStatus") List<String> dbPushbackStatus, @Param("rpcDbVerificationAllowedStatus") List<String> rpcDbVerificationAllowedStatus);


    @Query(value = "SELECT new ApplicationMaster( "
            + "appMaster1.applicationId AS applicationId, "
            + "appMaster1.memberId AS customerId, "
            + "custdtls.customerName AS customerName, "
            + "appMaster1.branchName AS branchName, "
            + "CONCAT("
            + "FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60) * 60), 'S|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600) * 60), 'M|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400) * 24), 'H|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400), 'D' ) AS rpcTAT,"
            + "loanDtl.loanAmount AS loanAmount,"
            + " appMaster1.applicationStatus as applicationStatus,'', appMaster1.productCode as productCode, appMaster1.kendraId as kendraId) "
            + "FROM ApplicationMaster appMaster1 "
            + "LEFT JOIN LoanDetails loanDtl ON appMaster1.applicationId = loanDtl.applicationId "
            + "LEFT JOIN ApplicationWorkflow applnWf1 ON appMaster1.applicationId = applnWf1.applicationId "
            + "LEFT JOIN CustomerDetails custdtls ON appMaster1.applicationId = custdtls.applicationId "
            + "AND custdtls.customerType = 'Applicant' "
            + "WHERE appMaster1.branchId IN :branchIds AND appMaster1.productCode IN :productCodes "
            + " AND appMaster1.applicationStatus IN :status AND applnWf1.workflowSeqNum = (SELECT max(applnWf2.workflowSeqNum) "
            + "FROM ApplicationWorkflow applnWf2 "
            + "WHERE applnWf2.applicationId = appMaster1.applicationId) "
            + " GROUP BY appMaster1.applicationId, "
            + " appMaster1.memberId, "
            + " custdtls.customerName,"
            + " appMaster1.branchName, "
            + " loanDtl.loanAmount, "
            + " appMaster1.applicationStatus, appMaster1.createTs, "
            + " applnWf1.createTs, applnWf1.workflowSeqNum , appMaster1.productCode, appMaster1.kendraId "
            + " ORDER BY EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) ASC")
     Page<ApplicationMaster> fetchNewDashboardApplications(
            Pageable page, @Param("branchIds") List<String> branchIds,
            @Param("status") List<String> status, List<String> productCodes);
    
    @Query(value = "SELECT new ApplicationMaster( "
            + "appMaster1.applicationId AS applicationId, "
            + "appMaster1.memberId AS customerId, "
            + "custdtls.customerName AS customerName, "
            + "appMaster1.branchName AS branchName, "
            + "CONCAT("
            + "FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60) * 60), 'S|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600) * 60), 'M|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400) * 24), 'H|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400), 'D' ) AS rpcTAT,"
            + "loanDtl.loanAmount AS loanAmount,"
            + " appMaster1.applicationStatus as applicationStatus,'', appMaster1.productCode as productCode, appMaster1.kendraId as kendraId) "
            + "FROM ApplicationMaster appMaster1 "
            + "LEFT JOIN LoanDetails loanDtl ON appMaster1.applicationId = loanDtl.applicationId "
            + "LEFT JOIN ApplicationWorkflow applnWf1 ON appMaster1.applicationId = applnWf1.applicationId "
            + "LEFT JOIN CustomerDetails custdtls ON appMaster1.applicationId = custdtls.applicationId "
            + "AND custdtls.customerType = 'Applicant' "
            + "WHERE appMaster1.branchId IN :branchIds AND appMaster1.productCode IN :productCodes AND appMaster1.declarationFlag = :iexceedFlag "
            + " AND appMaster1.applicationStatus IN :status AND applnWf1.workflowSeqNum = (SELECT max(applnWf2.workflowSeqNum) "
            + "FROM ApplicationWorkflow applnWf2 "
            + "WHERE applnWf2.applicationId = appMaster1.applicationId) "
            + " GROUP BY appMaster1.applicationId, "
            + " appMaster1.memberId, "
            + " custdtls.customerName,"
            + " appMaster1.branchName, "
            + " loanDtl.loanAmount, "
            + " appMaster1.applicationStatus, appMaster1.createTs, "
            + " applnWf1.createTs, applnWf1.workflowSeqNum , appMaster1.productCode, appMaster1.kendraId "
            + " ORDER BY EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) ASC")
     Page<ApplicationMaster> fetchRPCNewDashboardApplications(
            Pageable page, @Param("branchIds") List<String> branchIds,
            @Param("status") List<String> status, List<String> productCodes, String iexceedFlag);

    @Query(value = "SELECT new ApplicationMaster( "
            + "appMaster1.applicationId AS applicationId, "
            + "appMaster1.memberId AS customerId, "
            + "custdtls.customerName AS customerName, "
            + "appMaster1.branchName AS branchName, "
            + "CONCAT("
            + "FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60) * 60), 'S|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600) * 60), 'M|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400) * 24), 'H|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400), 'D' ) AS rpcTAT,"
            + "loanDtl.loanAmount AS loanAmount,"
            + " appMaster1.applicationStatus as applicationStatus,'', appMaster1.productCode as productCode, appMaster1.kendraId as kendraId) "
            + "FROM ApplicationMaster appMaster1 "
            + "LEFT JOIN LoanDetails loanDtl ON appMaster1.applicationId = loanDtl.applicationId "
            + "LEFT JOIN ApplicationWorkflow applnWf1 ON appMaster1.applicationId = applnWf1.applicationId "
            + "LEFT JOIN CustomerDetails custdtls ON appMaster1.applicationId = custdtls.applicationId "
            + "AND custdtls.customerType = 'Applicant' "
            + "WHERE appMaster1.searchCode1 IN :kendraIds AND appMaster1.productCode IN :productCodes "
            + " AND appMaster1.applicationStatus IN :status AND applnWf1.workflowSeqNum = (SELECT max(applnWf2.workflowSeqNum) "
            + "FROM ApplicationWorkflow applnWf2 "
            + "WHERE applnWf2.applicationId = appMaster1.applicationId) "
            + " GROUP BY appMaster1.applicationId, "
            + " appMaster1.memberId, "
            + " custdtls.customerName,"
            + " appMaster1.branchName, "
            + " loanDtl.loanAmount, "
            + " appMaster1.applicationStatus, appMaster1.createTs, "
            + " applnWf1.createTs, applnWf1.workflowSeqNum , appMaster1.productCode, appMaster1.kendraId "
            + " ORDER BY EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) ASC")
     Page<ApplicationMaster> fetchNewKMDashboardApplications(
            Pageable page, @Param("kendraIds") List<String> kendraIds,
            @Param("status") List<String> status, List<String> productCodes);
    
    @Query(value = " SELECT new ApplicationMaster( "
            + " appMaster1.applicationId AS applicationId, "
            + " appMaster1.memberId AS customerId, "
            + " custdtls.customerName AS customerName, "
            + " appMaster1.branchName AS branchName, "
            + " CONCAT("
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60) * 60), 'S|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600) * 60), 'M|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400) * 24), 'H|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400), 'D' ) AS rpcTAT,"
            + " loanDtl.loanAmount AS loanAmount,"
            + " appMaster1.applicationStatus as applicationStatus,'', appMaster1.productCode as productCode, appMaster1.kendraId as kendraId) "
            + " FROM ApplicationMaster appMaster1 "
            + " LEFT JOIN LoanDetails loanDtl ON appMaster1.applicationId = loanDtl.applicationId "
            + " LEFT JOIN ApplicationWorkflow applnWf1 ON appMaster1.applicationId = applnWf1.applicationId "
            + " AND applnWf1.workflowSeqNum = (SELECT max(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 WHERE applnWf2.applicationId = appMaster1.applicationId) "
            + " LEFT JOIN ApplicationWorkflow prevAw ON appMaster1.applicationId = prevAw.applicationId AND prevAw.workflowSeqNum = ( "
            + " SELECT MAX(p.workflowSeqNum) FROM ApplicationWorkflow p WHERE p.applicationId = applnWf1.applicationId AND p.workflowSeqNum < applnWf1.workflowSeqNum ) "
            + " LEFT JOIN CustomerDetails custdtls ON appMaster1.applicationId = custdtls.applicationId "
            + " AND custdtls.customerType = 'Applicant' "
            + " WHERE appMaster1.searchCode1 IN :kendraIds AND appMaster1.productCode IN :productCodes "
            + " AND ((appMaster1.applicationStatus IN :status "
            + " AND applnWf1.createTs < :lucWaitDateTime ) OR (appMaster1.applicationStatus = 'LUC' AND prevAw.applicationStatus = 'PENDINGLUCVERIFICATION')) "
            + " GROUP BY appMaster1.applicationId, "
            + " appMaster1.memberId, "
            + " custdtls.customerName,"
            + " appMaster1.branchName, "
            + " loanDtl.loanAmount, "
            + " appMaster1.applicationStatus, appMaster1.createTs, "
            + " applnWf1.createTs, applnWf1.workflowSeqNum , appMaster1.productCode, appMaster1.kendraId "
            + " ORDER BY EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) ASC")
     Page<ApplicationMaster> lucKMDashboardApplications(
            Pageable page, @Param("kendraIds") List<String> kendraIds,
            @Param("status") List<String> status, List<String> productCodes, LocalDateTime lucWaitDateTime);

    @Query(value = "SELECT new ApplicationMaster( "
            + "appMaster1.applicationId AS applicationId, "
            + "appMaster1.memberId AS customerId, "
            + "custdtls.customerName AS customerName, "
            + "appMaster1.branchName AS branchName, "
            + "CONCAT("
            + "FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60) * 60), 'S|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600) * 60), 'M|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400) * 24), 'H|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400), 'D' ) AS rpcTAT,"
            + "loanDtl.loanAmount AS loanAmount,"
            + " appMaster1.applicationStatus as applicationStatus,'', appMaster1.productCode as productCode, appMaster1.kendraId as kendraId) "
            + "FROM ApplicationMaster appMaster1 "
            + "LEFT JOIN LoanDetails loanDtl ON appMaster1.applicationId = loanDtl.applicationId "
            + "LEFT JOIN ApplicationWorkflow applnWf1 ON appMaster1.applicationId = applnWf1.applicationId AND applnWf1.workflowSeqNum = (SELECT max(applnWf2.workflowSeqNum)  FROM ApplicationWorkflow applnWf2 "
            + "WHERE applnWf2.applicationId = appMaster1.applicationId) "
            + " LEFT JOIN ApplicationWorkflow prevAw ON appMaster1.applicationId = prevAw.applicationId AND prevAw.workflowSeqNum = ( "
            + " SELECT MAX(p.workflowSeqNum) FROM ApplicationWorkflow p WHERE p.applicationId = applnWf1.applicationId AND p.workflowSeqNum < applnWf1.workflowSeqNum ) "
            + "LEFT JOIN CustomerDetails custdtls ON appMaster1.applicationId = custdtls.applicationId "
            + "AND custdtls.customerType = 'Applicant' "
            + "WHERE appMaster1.branchId IN :branchIds AND appMaster1.productCode IN :productCodes "
            + " AND ((appMaster1.applicationStatus IN :status "
            + " AND applnWf1.createTs < :lucWaitDateTime ) OR (appMaster1.applicationStatus = 'LUC' AND prevAw.applicationStatus = 'PENDINGLUCVERIFICATION')) "
            + " GROUP BY appMaster1.applicationId, "
            + " appMaster1.memberId, "
            + " custdtls.customerName,"
            + " appMaster1.branchName, "
            + " loanDtl.loanAmount, "
            + " appMaster1.applicationStatus, appMaster1.createTs, "
            + " applnWf1.createTs, applnWf1.workflowSeqNum , appMaster1.productCode, appMaster1.kendraId "
            + " ORDER BY EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) ASC")
    Page<ApplicationMaster> fetchLUCDashboardApplications(
            Pageable page, @Param("branchIds") List<String> branchIds,
            @Param("status") List<String> status, List<String> productCodes, LocalDateTime lucWaitDateTime);

    @Query(value = "SELECT new ApplicationMaster( "
            + "appMaster1.applicationId AS applicationId, "
            + "appMaster1.memberId AS customerId, "
            + "custdtls.customerName AS customerName, "
            + "appMaster1.branchName AS branchName, "
            + "CONCAT("
            + "FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60) * 60), 'S|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600) * 60), 'M|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400) * 24), 'H|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400), 'D' ) AS rpcTAT,"
            + "loanDtl.loanAmount AS loanAmount,"
            + " appMaster1.applicationStatus as applicationStatus,'', appMaster1.productCode as productCode, appMaster1.kendraId as kendraId) "
            + "FROM ApplicationMaster appMaster1 "
            + "LEFT JOIN LoanDetails loanDtl ON appMaster1.applicationId = loanDtl.applicationId "
            + "LEFT JOIN ApplicationWorkflow applnWf1 ON appMaster1.applicationId = applnWf1.applicationId "
            + "LEFT JOIN CustomerDetails custdtls ON appMaster1.applicationId = custdtls.applicationId "
            + "AND custdtls.customerType = 'Applicant' "
            + "WHERE appMaster1.searchCode1 IN :kendraIds AND appMaster1.productCode IN :productCodes "
            + " AND appMaster1.applicationStatus IN :status AND applnWf1.workflowSeqNum = (SELECT max(applnWf2.workflowSeqNum) "
            + "FROM ApplicationWorkflow applnWf2 "
            + "WHERE applnWf2.applicationId = appMaster1.applicationId) AND applnWf1.createTs < :rejectionExpiryDateTime "
            + " GROUP BY appMaster1.applicationId, "
            + " appMaster1.memberId, "
            + " custdtls.customerName,"
            + " appMaster1.branchName, "
            + " loanDtl.loanAmount, "
            + " appMaster1.applicationStatus, appMaster1.createTs, "
            + " applnWf1.createTs, applnWf1.workflowSeqNum , appMaster1.productCode, appMaster1.kendraId "
            + " ORDER BY EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) ASC")
    Page<ApplicationMaster> fetchNewKMDashboardRejectedApplications(
            Pageable page, @Param("kendraIds") List<String> kendraIds,
            @Param("status") List<String> status, List<String> productCodes, LocalDateTime rejectionExpiryDateTime);


    @Query(value = "SELECT new ApplicationMaster( "
            + "appMaster1.applicationId AS applicationId, "
            + "appMaster1.memberId AS customerId, "
            + "custdtls.customerName AS customerName, "
            + "appMaster1.branchName AS branchName, "
            + "CONCAT("
            + "FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60) * 60), 'S|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600) * 60), 'M|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400) * 24), 'H|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400), 'D' ) AS rpcTAT,"
            + "loanDtl.loanAmount AS loanAmount,"
            + " appMaster1.applicationStatus as applicationStatus,'', appMaster1.productCode as productCode, appMaster1.kendraId as kendraId) "
            + "FROM ApplicationMaster appMaster1 "
            + "LEFT JOIN LoanDetails loanDtl ON appMaster1.applicationId = loanDtl.applicationId "
            + "LEFT JOIN ApplicationWorkflow applnWf1 ON appMaster1.applicationId = applnWf1.applicationId "
            + "LEFT JOIN CustomerDetails custdtls ON appMaster1.applicationId = custdtls.applicationId "
            + "AND custdtls.customerType = 'Applicant' "
            + "WHERE appMaster1.branchId IN :branchIds  AND appMaster1.productCode IN :productCodes "
            + " AND appMaster1.applicationStatus IN :status AND applnWf1.workflowSeqNum = (SELECT max(applnWf2.workflowSeqNum) "
            + "FROM ApplicationWorkflow applnWf2 "
            + "WHERE applnWf2.applicationId = appMaster1.applicationId) "
            + " AND EXISTS ("
            + " SELECT applnwf2.applicationStatus "
            + " FROM ApplicationWorkflow applnwf2 "
            + " WHERE applnwf2.applicationId = appMaster1.applicationId "
            + " AND applnwf2.workflowSeqNum = ( "
            + " SELECT MAX(applnwf3.workflowSeqNum) "
            + " FROM ApplicationWorkflow applnwf3 "
            + " WHERE applnwf3.applicationId = appMaster1.applicationId "
            + " AND applnwf3.workflowSeqNum < applnWf1.workflowSeqNum "
            + " )    AND applnwf2.applicationStatus IN :previousStatus )"
            + " GROUP BY appMaster1.applicationId, "
            + " appMaster1.memberId, "
            + " custdtls.customerName,"
            + " appMaster1.branchName, "
            + " loanDtl.loanAmount, "
            + " appMaster1.applicationStatus, appMaster1.createTs, "
            + " applnWf1.createTs, applnWf1.workflowSeqNum ,appMaster1.productCode, appMaster1.kendraId "
            + " ORDER BY EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) ASC")
     Page<ApplicationMaster> fetchDashboardRejectionPushbackApplications(
            Pageable page, @Param("branchIds") List<String> branchIds,
            @Param("status") List<String> status, @Param("previousStatus") List<String> previousStatus, List<String> productCodes);

    @Query(value = "SELECT new ApplicationMaster( "
            + "appMaster1.applicationId AS applicationId, "
            + "appMaster1.memberId AS customerId, "
            + "custdtls.customerName AS customerName, "
            + "appMaster1.branchName AS branchName, "
            + "CONCAT("
            + "FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60) * 60), 'S|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600) * 60), 'M|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400) * 24), 'H|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400), 'D' ) AS rpcTAT,"
            + "loanDtl.loanAmount AS loanAmount,"
            + " appMaster1.applicationStatus as applicationStatus,'', appMaster1.productCode as productCode, appMaster1.kendraId as kendraId) "
            + "FROM ApplicationMaster appMaster1 "
            + "LEFT JOIN LoanDetails loanDtl ON appMaster1.applicationId = loanDtl.applicationId "
            + "LEFT JOIN ApplicationWorkflow applnWf1 ON appMaster1.applicationId = applnWf1.applicationId "
            + "LEFT JOIN CustomerDetails custdtls ON appMaster1.applicationId = custdtls.applicationId "
            + "AND custdtls.customerType = 'Applicant' "
            + "WHERE appMaster1.branchId IN :branchIds  AND appMaster1.productCode IN :productCodes "
            + " AND appMaster1.applicationStatus IN :status AND applnWf1.workflowSeqNum = (SELECT max(applnWf2.workflowSeqNum) "
            + "FROM ApplicationWorkflow applnWf2 "
            + "WHERE applnWf2.applicationId = appMaster1.applicationId) "
            + " AND NOT EXISTS ("
            + " SELECT applnwf2.applicationStatus "
            + " FROM ApplicationWorkflow applnwf2 "
            + " WHERE applnwf2.applicationId = appMaster1.applicationId "
            + " AND applnwf2.workflowSeqNum = ( "
            + " SELECT MAX(applnwf3.workflowSeqNum) "
            + " FROM ApplicationWorkflow applnwf3 "
            + " WHERE applnwf3.applicationId = appMaster1.applicationId "
            + " AND applnwf3.workflowSeqNum < applnWf1.workflowSeqNum "
            + " )    AND applnwf2.applicationStatus IN :previousStatus )"
            + " GROUP BY appMaster1.applicationId, "
            + " appMaster1.memberId, "
            + " custdtls.customerName,"
            + " appMaster1.branchName, "
            + " loanDtl.loanAmount, "
            + " appMaster1.applicationStatus, appMaster1.createTs, "
            + " applnWf1.createTs, applnWf1.workflowSeqNum ,appMaster1.productCode, appMaster1.kendraId "
            + " ORDER BY EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) ASC")
     Page<ApplicationMaster> fetchNewDashboardFreshApplications(
            Pageable page, @Param("branchIds") List<String> branchIds,
            @Param("status") List<String> status, @Param("previousStatus") List<String> previousStatus, List<String> productCodes);

    @Query(value = "SELECT new ApplicationMaster( "
            + "appMaster1.applicationId AS applicationId, "
            + "appMaster1.memberId AS customerId, "
            + "custdtls.customerName AS customerName, "
            + "appMaster1.branchName AS branchName, "
            + "CONCAT("
            + "FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60) * 60), 'S|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600) * 60), 'M|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400) * 24), 'H|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400), 'D' ) AS rpcTAT,"
            + "loanDtl.loanAmount AS loanAmount,"
            + " appMaster1.applicationStatus as applicationStatus,'', appMaster1.productCode as productCode, appMaster1.kendraId as kendraId) "
            + "FROM ApplicationMaster appMaster1 "
            + "LEFT JOIN LoanDetails loanDtl ON appMaster1.applicationId = loanDtl.applicationId "
            + "LEFT JOIN ApplicationWorkflow applnWf1 ON appMaster1.applicationId = applnWf1.applicationId "
            + "LEFT JOIN CustomerDetails custdtls ON appMaster1.applicationId = custdtls.applicationId "
            + "AND custdtls.customerType = 'Applicant' "
            + "WHERE appMaster1.searchCode1 IN :KendraIds  "
            + " AND appMaster1.applicationStatus IN :status AND applnWf1.workflowSeqNum = (SELECT max(applnWf2.workflowSeqNum) "
            + "FROM ApplicationWorkflow applnWf2 "
            + "WHERE applnWf2.applicationId = appMaster1.applicationId) AND appMaster1.productCode IN :productCodes "
            + " AND EXISTS ("
            + " SELECT applnwf2.applicationStatus "
            + " FROM ApplicationWorkflow applnwf2 "
            + " WHERE applnwf2.applicationId = appMaster1.applicationId "
            + " AND applnwf2.workflowSeqNum = ( "
            + " SELECT MAX(applnwf3.workflowSeqNum) "
            + " FROM ApplicationWorkflow applnwf3 "
            + " WHERE applnwf3.applicationId = appMaster1.applicationId "
            + " AND applnwf3.workflowSeqNum < applnWf1.workflowSeqNum "
            + " )    AND applnwf2.applicationStatus IN :previousStatus )"
            + " GROUP BY appMaster1.applicationId, "
            + " appMaster1.memberId, "
            + " custdtls.customerName,"
            + " appMaster1.branchName, "
            + " loanDtl.loanAmount, "
            + " appMaster1.applicationStatus, appMaster1.createTs, "
            + " applnWf1.createTs, applnWf1.workflowSeqNum ,appMaster1.productCode, appMaster1.kendraId "
            + " ORDER BY EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) ASC")
     Page<ApplicationMaster> fetchKMDashboardRejectionPushbackApplications(
            Pageable page, @Param("KendraIds") List<String> KendraIds,
            @Param("status") List<String> status, @Param("previousStatus") List<String> previousStatus, List<String> productCodes);


    @Query(value = "SELECT new ApplicationMaster( "
            + "appMaster1.applicationId AS applicationId, "
            + "appMaster1.memberId AS customerId, "
            + "custdtls.customerName AS customerName, "
            + "appMaster1.branchName AS branchName, "
            + "CONCAT("
            + "FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60) * 60), 'S|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600) * 60), 'M|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400) * 24), 'H|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400), 'D' ) AS rpcTAT,"
            + "loanDtl.loanAmount AS loanAmount,"
            + " appMaster1.applicationStatus as applicationStatus,'', appMaster1.productCode as productCode, appMaster1.kendraId as kendraId) "
            + "FROM ApplicationMaster appMaster1 "
            + "LEFT JOIN LoanDetails loanDtl ON appMaster1.applicationId = loanDtl.applicationId "
            + "LEFT JOIN ApplicationWorkflow applnWf1 ON appMaster1.applicationId = applnWf1.applicationId "
            + "LEFT JOIN CustomerDetails custdtls ON appMaster1.applicationId = custdtls.applicationId "
            + "AND custdtls.customerType = 'Applicant' "
            + "WHERE appMaster1.branchId IN :branchIds AND appMaster1.productCode IN :productCodes "
            + " AND appMaster1.applicationStatus IN :status AND applnWf1.workflowSeqNum = (SELECT max(applnWf2.workflowSeqNum) "
            + "FROM ApplicationWorkflow applnWf2 "
            + "WHERE applnWf2.applicationId = appMaster1.applicationId) "
            + " AND EXISTS ( "
            + "     SELECT 1 FROM DeviationRATracker deviationRa1 WHERE deviationRa1.applicationId = appMaster1.applicationId AND "
            + "     deviationRa1.authority IN :role "
            + "     AND deviationRa1.recordType IN :recordType ) "
            + " GROUP BY appMaster1.applicationId, "
            + " appMaster1.memberId, "
            + " custdtls.customerName,"
            + " appMaster1.branchName, "
            + " loanDtl.loanAmount, "
            + " appMaster1.applicationStatus, appMaster1.createTs, "
            + " applnWf1.createTs, applnWf1.workflowSeqNum , appMaster1.productCode, appMaster1.kendraId "
            + " ORDER BY EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) ASC")
     Page<ApplicationMaster> fetchDeviationRADashboardApplication(
            List<String> branchIds, List<String> status,
            List<String> role, List<String> recordType, Pageable page, List<String> productCodes);

    @Query(value = "SELECT new ApplicationMaster( "
            + "appMaster1.applicationId AS applicationId, "
            + "appMaster1.memberId AS customerId, "
            + "custdtls.customerName AS customerName, "
            + "appMaster1.branchName AS branchName, "
            + "CONCAT("
            + "FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60) * 60), 'S|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600) * 60), 'M|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400) * 24), 'H|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400), 'D' ) AS rpcTAT,"
            + "loanDtl.loanAmount AS loanAmount,"
            + " appMaster1.applicationStatus as applicationStatus,'', appMaster1.productCode as productCode, appMaster1.kendraId as kendraId) "
            + "FROM ApplicationMaster appMaster1 "
            + "LEFT JOIN LoanDetails loanDtl ON appMaster1.applicationId = loanDtl.applicationId "
            + "LEFT JOIN ApplicationWorkflow applnWf1 ON appMaster1.applicationId = applnWf1.applicationId "
            + "LEFT JOIN CustomerDetails custdtls ON appMaster1.applicationId = custdtls.applicationId "
            + "AND custdtls.customerType = 'Applicant' "
            + "WHERE appMaster1.searchCode1 IN :kendraIds AND appMaster1.productCode IN :productCodes AND EXISTS ("
            + " SELECT 1 FROM DeviationRATracker deviationRa1 WHERE deviationRa1.applicationId = appMaster1.applicationId AND "
            + " deviationRa1.authority IN :role AND deviationRa1.recordType IN :recordType ) "
            + " AND appMaster1.applicationStatus IN :status AND applnWf1.workflowSeqNum = (SELECT max(applnWf2.workflowSeqNum) "
            + "FROM ApplicationWorkflow applnWf2 "
            + "WHERE applnWf2.applicationId = appMaster1.applicationId) GROUP BY appMaster1.applicationId, "
            + "appMaster1.memberId, "
            + "custdtls.customerName,"
            + "appMaster1.branchName, "
            + "loanDtl.loanAmount, "
            + "appMaster1.applicationStatus, appMaster1.createTs, applnWf1.createTs, applnWf1.workflowSeqNum, appMaster1.productCode, appMaster1.kendraId "
            + " ORDER BY EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) ASC ")
     Page<ApplicationMaster> fetchDeviationRAKMDashboardApplication(
            List<String> kendraIds, List<String> status,
            List<String> role, List<String> recordType, Pageable page, List<String> productCodes);

    @Query(value = "SELECT new ApplicationMaster( "
            + "appMaster1.applicationId AS applicationId, "
            + "appMaster1.memberId AS customerId, "
            + "custdtls.customerName AS customerName, "
            + "appMaster1.branchName AS branchName, "
            + "CONCAT("
            + "FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60) * 60), 'S|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600) * 60), 'M|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400) * 24), 'H|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400), 'D' ) AS rpcTAT,"
            + "loanDtl.loanAmount AS loanAmount,"
            + " appMaster1.applicationStatus as applicationStatus,"
            + "CASE WHEN MAX(applnWf1.workflowSeqNum) IN :freshCaseSeqNum THEN 'false' ELSE 'true' END AS isRework) "
            + "FROM ApplicationMaster appMaster1 "
            + "LEFT JOIN LoanDetails loanDtl ON appMaster1.applicationId = loanDtl.applicationId "
            + "LEFT JOIN ApplicationWorkflow applnWf1 ON appMaster1.applicationId = applnWf1.applicationId "
            + "LEFT JOIN CustomerDetails custdtls ON appMaster1.applicationId = custdtls.applicationId "
            + "AND custdtls.customerType = 'Applicant' " + "WHERE appMaster1.searchCode1 IN :kendraIds "
            + "AND appMaster1.applicationStatus in :status AND appMaster1.productCode IN :productCodes "
            + "AND applnWf1.workflowSeqNum = (SELECT max(applnWf2.workflowSeqNum) "
            + "FROM ApplicationWorkflow applnWf2 " + "WHERE applnWf2.applicationId = appMaster1.applicationId) "
            + "AND ( " + "    (:role = 'RPC_MAKER' AND ( "
            + "(:filterType = 'all' "
            + "AND ("
            + "(appMaster1.applicationStatus IN ('APPROVED') AND "
            + "NOT EXISTS (SELECT 1 FROM ApplicationWorkflow wf"
            + "        WHERE wf.applicationId = appMaster1.applicationId "
            + "          AND wf.applicationStatus IN :reworkStages)) "
            + "OR (appMaster1.applicationStatus IN ('APPROVED') AND EXISTS (SELECT 1 FROM ApplicationWorkflow wf "
            + "       WHERE wf.applicationId = appMaster1.applicationId"
            + "         AND wf.applicationStatus IN :pushback)) "
            + "OR (appMaster1.applicationStatus IN (:rpcPushBack) AND EXISTS (SELECT 1 FROM ApplicationWorkflow applnWf3"
            + "         WHERE applnWf3.applicationId = appMaster1.applicationId AND "
            + "applnWf3.workflowSeqNum = (SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 WHERE applnWf2.applicationId = appMaster1.applicationId) "
            + "          AND applnWf3.applicationStatus IN :rpcPushBack) AND NOT EXISTS("
            + "SELECT 1 FROM ApplicationWorkflow applnWf3 WHERE applnWf3.applicationId = appMaster1.applicationId AND "
            + "applnWf3.workflowSeqNum = (SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 WHERE applnWf2.applicationId = appMaster1.applicationId) AND applnWf3.createdBy = :userId) ) "
            + ")) OR "
            + "        (:filterType = 'freshCases'"
            + "            AND appMaster1.applicationStatus = 'APPROVED' AND NOT EXISTS (SELECT 1 FROM ApplicationWorkflow wf "
            + "                WHERE wf.applicationId = appMaster1.applicationId "
            + "                AND wf.applicationStatus IN :reworkStages)) OR "
            + "        (:filterType = 'reworkCases' "
            + "           AND appMaster1.applicationStatus = 'APPROVED' AND EXISTS (SELECT 1 FROM ApplicationWorkflow wf "
            + "                WHERE wf.applicationId = appMaster1.applicationId "
            + "                AND wf.applicationStatus IN :pushback)) OR "
            + "        (:filterType = 'rpcCheckerToMaker' AND appMaster1.applicationStatus = :rpcPushBack "
            + "AND EXISTS(SELECT 1 FROM ApplicationWorkflow applnWf3 WHERE applnWf3.applicationId = appMaster1.applicationId AND "
            + "applnWf3.workflowSeqNum = (SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 WHERE applnWf2.applicationId = appMaster1.applicationId) "
            + "          AND applnWf3.applicationStatus IN :rpcPushBack) AND NOT EXISTS("
            + "SELECT 1 FROM ApplicationWorkflow applnWf3 WHERE applnWf3.applicationId = appMaster1.applicationId AND "
            + "applnWf3.workflowSeqNum = (SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 WHERE applnWf2.applicationId = appMaster1.applicationId) AND applnWf3.createdBy = :userId) ) "
            + "    )) "
            + "    OR " + "    (:role = 'RPC_CHECKER' AND ( "
            + "(:filterType = 'all' "
            + "AND appMaster1.applicationStatus = 'PENDINGFORRPCVERIFICATION' "
            + "AND ( "
            + "    (NOT EXISTS (SELECT 1 FROM ApplicationWorkflow wf "
            + "                 WHERE wf.applicationId = appMaster1.applicationId "
            + "                 AND wf.applicationStatus IN :reworkStages "
            + "                 ) AND NOT EXISTS ("
            + "   SELECT 1 FROM ApplicationWorkflow wf "
            + " WHERE wf.applicationId = appMaster1.applicationId "
            + " AND wf.createdBy = :userId AND wf.workflowSeqNum = (SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 WHERE applnWf2.applicationId = appMaster1.applicationId)"
            + " )) "
            + "    OR (EXISTS (SELECT 1 FROM ApplicationWorkflow wf "
            + "                WHERE wf.applicationId = appMaster1.applicationId "
            + "                AND wf.applicationStatus IN :reworkStages "
            + "                ) AND NOT EXISTS ("
            + "   SELECT 1 FROM ApplicationWorkflow wf "
            + " WHERE wf.applicationId = appMaster1.applicationId "
            + " AND wf.createdBy = :userId AND wf.workflowSeqNum = (SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 WHERE applnWf2.applicationId = appMaster1.applicationId)"
            + " ))"
            + ")) OR "
            + "(:filterType = 'freshCases' "
            + "  AND appMaster1.applicationStatus = 'PENDINGFORRPCVERIFICATION' "
            + "AND NOT EXISTS ( "
            + "  SELECT 1 FROM ApplicationWorkflow wf "
            + "WHERE wf.applicationId = appMaster1.applicationId "
            + " AND wf.applicationStatus IN :reworkStages) "
            + " AND NOT EXISTS ("
            + "   SELECT 1 FROM ApplicationWorkflow wf "
            + " WHERE wf.applicationId = appMaster1.applicationId "
            + " AND wf.createdBy = :userId AND wf.workflowSeqNum = (SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 WHERE applnWf2.applicationId = appMaster1.applicationId)"
            + " )) OR "
            + "        (:filterType = 'reworkCases'"
            + "           AND appMaster1.applicationStatus = 'PENDINGFORRPCVERIFICATION' AND EXISTS (SELECT 1 FROM ApplicationWorkflow wf "
            + "                WHERE wf.applicationId = appMaster1.applicationId "
            + "                AND wf.applicationStatus IN :reworkStages )" + " AND NOT EXISTS ("
            + "   SELECT 1 FROM ApplicationWorkflow wf "
            + " WHERE wf.applicationId = appMaster1.applicationId "
            + " AND wf.createdBy = :userId AND wf.workflowSeqNum = (SELECT MAX(applnWf2.workflowSeqNum) FROM ApplicationWorkflow applnWf2 WHERE applnWf2.applicationId = appMaster1.applicationId)"
            + " )) " + "    )) "
            + ") "
            + " GROUP BY appMaster1.applicationId, "
            + "appMaster1.memberId, "
            + "custdtls.customerName,"
            + "appMaster1.branchName, "
            + "loanDtl.loanAmount, "
            + "appMaster1.applicationStatus, appMaster1.createTs, applnWf1.createTs, applnWf1.workflowSeqNum "
            + "ORDER BY EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) ASC")
    //ascending order since epoch works opposite to timestamp in terms of ordering
     Page<ApplicationMaster> fetchRPCKMDashBoardApplications(@Param("status") List<String> status,
                                                                   @Param("kendraIds") List<String> kendraIds, Pageable pageable,
                                                                   @Param("role") String role, @Param("filterType") String filterType,
                                                                   @Param("reworkStages") List<String> reworkStages, @Param("pushback") String pushback,
                                                                   @Param("rpcPushBack") String rpcPushBack, @Param("freshCaseSeqNum") List<Integer> freshCaseSeqNum, String userId, List<String> productCodes);


    @Query(value = "SELECT new ApplicationMaster( "
            + "appMaster1.applicationId AS applicationId, "
            + "appMaster1.memberId AS customerId, "
            + "custdtls.customerName AS customerName, "
            + "appMaster1.branchName AS branchName, "
            + "CONCAT("
            + "FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60) * 60), 'S|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600) * 60), 'M|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400) * 24), 'H|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400), 'D' ) AS rpcTAT,"
            + "loanDtl.loanAmount AS loanAmount,"
            + " appMaster1.applicationStatus as applicationStatus,'', appMaster1.productCode as productCode, appMaster1.kendraId as kendraId) "
            + "FROM ApplicationMaster appMaster1 "
            + "LEFT JOIN LoanDetails loanDtl ON appMaster1.applicationId = loanDtl.applicationId "
            + "LEFT JOIN ApplicationWorkflow applnWf1 ON appMaster1.applicationId = applnWf1.applicationId "
            + "LEFT JOIN CustomerDetails custdtls ON appMaster1.applicationId = custdtls.applicationId "
            + "AND custdtls.customerType = 'Applicant' "
            + " LEFT JOIN SanctionMaster sanctionMaster on appMaster1.productCode = sanctionMaster.product "
            + " WHERE appMaster1.branchId IN :branchIds "
            + " AND appMaster1.applicationStatus IN :status AND applnWf1.workflowSeqNum = (SELECT max(applnWf2.workflowSeqNum) "
            + "FROM ApplicationWorkflow applnWf2 "
            + "WHERE applnWf2.applicationId = appMaster1.applicationId) AND appMaster1.productCode IN :productCodes "
            + "AND ("
            + "    (:userRoleKey = 'BM' AND sanctionMaster.bm = 'Y') OR "
            + "    (:userRoleKey = 'AM' AND sanctionMaster.am = 'Y') OR "
            + "    (:userRoleKey = 'RM' AND sanctionMaster.rm = 'Y') OR "
            + "    (:userRoleKey = 'DM' AND sanctionMaster.dm = 'Y') "
            + ") "
            + " AND (loanDtl.bmRecommendedLoanAmount BETWEEN sanctionMaster.minValue AND sanctionMaster.maxValue) "
            + " GROUP BY appMaster1.applicationId, "
            + " appMaster1.memberId, "
            + " custdtls.customerName,"
            + " appMaster1.branchName, "
            + " loanDtl.loanAmount, "
            + " loanDtl.bmRecommendedLoanAmount, "
            + " appMaster1.applicationStatus, appMaster1.createTs, "
            + " applnWf1.createTs, applnWf1.workflowSeqNum , appMaster1.productCode, appMaster1.kendraId "
            + " ORDER BY EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) ASC")
     Page<ApplicationMaster> fetchNewDashboardSanctionApplications(
            Pageable page, @Param("branchIds") List<String> branchIds,
            @Param("status") List<String> status, @Param("userRoleKey") String userRoleKey, List<String> productCodes);

    @Query(value = "SELECT new ApplicationMaster( "
            + "appMaster1.applicationId AS applicationId, "
            + "appMaster1.memberId AS customerId, "
            + "custdtls.customerName AS customerName, "
            + "appMaster1.branchName AS branchName, "
            + "CONCAT("
            + "FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60) * 60), 'S|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 60 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600) * 60), 'M|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 3600 "
            + "    - FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400) * 24), 'H|',"
            + " FLOOR(EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) / 86400), 'D' ) AS rpcTAT,"
            + "loanDtl.loanAmount AS loanAmount,"
            + " appMaster1.applicationStatus as applicationStatus,'', appMaster1.productCode as productCode, appMaster1.kendraId as kendraId) "
            + "FROM ApplicationMaster appMaster1 "
            + "LEFT JOIN LoanDetails loanDtl ON appMaster1.applicationId = loanDtl.applicationId "
            + "LEFT JOIN ApplicationWorkflow applnWf1 ON appMaster1.applicationId = applnWf1.applicationId "
            + "LEFT JOIN CustomerDetails custdtls ON appMaster1.applicationId = custdtls.applicationId "
            + "AND custdtls.customerType = 'Applicant' "
            + " LEFT JOIN SanctionMaster sanctionMaster on appMaster1.productCode = sanctionMaster.product "
            + " LEFT JOIN CibilDetails cbDtls on appMaster1.applicationId = cbDtls.applicationId AND custdtls.custDtlId != cbDtls.custDtlId "
            + " WHERE appMaster1.branchId IN :branchIds AND appMaster1.productCode IN :productCodes  "
            + " AND appMaster1.applicationStatus IN :status AND applnWf1.workflowSeqNum = (SELECT max(applnWf2.workflowSeqNum) "
            + "FROM ApplicationWorkflow applnWf2 "
            + "WHERE applnWf2.applicationId = appMaster1.applicationId) "
            + "AND ("
            + "    (:userRoleKey = 'BM' AND sanctionMaster.bm = 'Y') OR "
            + "    (:userRoleKey = 'AM' AND sanctionMaster.am = 'Y') OR "
            + "    (:userRoleKey = 'RM' AND sanctionMaster.rm = 'Y') OR "
            + "    (:userRoleKey = 'DM' AND sanctionMaster.dm = 'Y') "
            + ") "
            + " AND cbDtls.eligibleAmt BETWEEN sanctionMaster.minValue AND sanctionMaster.maxValue "
            + " GROUP BY appMaster1.applicationId, "
            + " appMaster1.memberId, "
            + " custdtls.customerName,"
            + " appMaster1.branchName, "
            + " loanDtl.loanAmount, "
            + " appMaster1.applicationStatus, appMaster1.createTs, "
            + " applnWf1.createTs, applnWf1.workflowSeqNum , appMaster1.productCode, appMaster1.kendraId "
            + " ORDER BY EXTRACT(EPOCH FROM AGE(CURRENT_TIMESTAMP, applnWf1.createTs)) ASC")
     Page<ApplicationMaster> fetchNewDashboardResanctionApplications(
            Pageable page, @Param("branchIds") List<String> branchIds,
            @Param("status") List<String> status, @Param("userRoleKey") String userRoleKey, List<String> productCodes);


    @Query("SELECT new ApplicationMaster( " +
            " '', ld.customerId, ld.fullName, " +
            " ld.glBranchName, '', 0, '', '', '1009', ld.kendraId) " +
            "FROM LeadDetails ld " +
            "WHERE ld.customerId NOT IN (SELECT app.memberId FROM ApplicationMaster app) " +
            "AND ld.kendraId IN :kendraIds")
    Page<ApplicationMaster> fetchUnactionedLeads(
            Pageable page, @Param("kendraIds") List<String> kendraIds
    );


    @Query(value = "SELECT new com.iexceed.appzillonbanking.cob.payload.MasterSearchQueryDTO( " +
            " appMaster.searchCode2, " +
            " custDtl.customerName, " +
            " appMaster.applicationId, " +
            " appMaster.branchId, " +
            " appMaster.branchName, " +
            " appMaster.searchCode1, " +
            " appMaster.kendraName, " +
            " appMaster.applicationStatus, '', " +
            " appMaster.productCode, " +
            " loanDetails.t24LoanId, " +
            " loanDetails.loanAmount) FROM ApplicationMaster appMaster " +
            " LEFT JOIN CustomerDetails custDtl ON custDtl.applicationId = appMaster.applicationId AND " +
            " custDtl.customerType = 'Applicant' " +
            " LEFT JOIN LoanDetails loanDetails ON loanDetails.applicationId = appMaster.applicationId " +
            " LEFT JOIN ApplicationWorkflow prevAppWorkFlow ON prevAppWorkFlow.applicationId = appMaster.applicationId " +
            " AND prevAppWorkFlow.workflowSeqNum = (SELECT MAX(applnWorkFlow.workflowSeqNum) from ApplicationWorkflow " +
            " applnWorkFlow WHERE applnWorkFlow.workflowSeqNum != (SELECT MAX(applnWorkFlow1.workflowSeqNum) FROM" +
            " ApplicationWorkflow applnWorkFlow1))" +
            " WHERE appMaster.applicationId = :searchValApplnId " +
            " OR appMaster.searchCode2 = :searchValuCustId or appMaster.workitemNo = :searchValWorkItemNo ")
    List<MasterSearchQueryDTO> masterSearchApplications(String searchValuCustId, String searchValApplnId, String searchValWorkItemNo);

}
