package com.iexceed.appzillonbanking.cob.core.utils;

public enum WorkflowStatus {
	INPROGRESS("INPROGRESS"),
	PENDING_FOR_VERIFICATION("PENDINGFORVERIFICATION"),
	PENDING_FOR_APPROVAL("PENDINGFORAPPROVAL"),
	PENDING_IN_QUEUE("PENDINGINQUEUE"),
	QUEUED_ASSIGNED("QUEUED/ASSIGNED"),
	NEXT_WF_STAGE_VERIFY_DOC("SUBMITFORVERIFYDOCUMENTS"),
	NEXT_WF_STAGE_APPROVE("SUBMITFORAPPROVAL"),
	NEXT_WF_STAGE_ASSIGNED_TO("ASSIGNEDTO"),
	NEXT_WF_STAGE_SUBMT_INITIATOR("SUBMITFORINITIATOR"),
	APPROVED("APPROVED"),
	PUSHBACK("PUSHBACK"),
	IPUSHBACK("IPUSHBACK"),
	REJECTED("REJECTED"),
	PENDINGFORRPCVERIFICATION("PENDINGFORRPCVERIFICATION"),
	RPCVERIFIED("RPCVERIFIED"),
	RPCPUSHBACK("RPCPUSHBACK"),
	PENDINGDEVIATION("PENDINGDEVIATION"),
	PENDINGREASSESSMENT("PENDINGREASSESSMENT"),
	CACOMPLETED("CACOMPLETED"),
	SANCTIONED("SANCTIONED"),
	RESANCTION("RESANCTION"),
	CAPUSHBACK("CAPUSHBACK"),
	DBKITGENERATED("DBKITGENERATED"),
	DBKITVERIFIED("DBKITVERIFIED"),
	DBPUSHBACK("DBPUSHBACK"),
	DISBURSED("DISBURSED"),
	PENDINGSERVICECALL("PENDINGSERVICECALL"),
	RPCBANKUPDATE("RPCBANKUPDATE"),
	PENDINGPRESANCTION("PENDINGPRESANCTION"),
    LUC("LUC"),
    PENDINGLUCVERIFICATION("PENDINGLUCVERIFICATION"),
    LUCVERIFIED("LUCVERIFIED");
	
	
	private final String value;
	
	WorkflowStatus(String value) {
		this.value = value;
	}
	
	public String getValue() {
		return value;
	}
}
